cru_inventory/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^helm/', admin.site.urls, name="helm"),
    url(r'^$', RedirectView.as_view(url=reverse_lazy("inv:items"), permanent=False)),
    url(r'^login/', auth_views.login, {'template_name': 'admin/login.html'}, name="login"),
    url(r'^logout/', auth_views.logout, {'next_page': reverse_lazy('login')}, name="logout"),
    url(r'^inventory/', include('inventory.urls', namespace='inv')),
]

inventory/urls.py
from django.conf.urls import url
from django.contrib import admin

from inventory.views import (
    AddItemView,
    ItemListView,
    ajax_checkout_item,
    ajax_checkin_item,
    ajax_useup_item,
    ajax_get_items_by_category_html,
    ajax_get_items_by_category,
    ajax_get_list_html,
    ajax_get_list_items_out_json,
    ajax_get_list_items_out_html,
    ajax_get_records_by_item_html)

urlpatterns = [
    url(r'^checkin/(?P<record_id>\d+)/', ajax_checkin_item, name='checkin'),
    url(r'^useup/(?P<record_id>\d+)/', ajax_useup_item, name='useup'),
    url(r'^checkout/', ajax_checkout_item, name='checkout'),
    url(r'^add/$', AddItemView.as_view(), name='add_item'),
    url(r'^items/$', ItemListView.as_view(), name='items'),
    url(r'^ajax_get_items_by_category/', ajax_get_items_by_category, name="ajax_get_items_by_category"),
    url(r'^ajax_get_items_by_category_html/', ajax_get_items_by_category_html, name="ajax_get_items_by_category_html"),
    url(r'^ajax_get_list_html/', ajax_get_list_html, name="ajax_get_list_html"),
    url(r'^ajax_get_list_items_out_json', ajax_get_list_items_out_json, name="ajax_get_list_items_out_json"),
    url(r'^ajax_get_list_items_out_html', ajax_get_list_items_out_html, name="ajax_get_list_items_out_html"),
    url(r'^ajax_get_records_by_item_html/', ajax_get_records_by_item_html, name="ajax_get_records_by_item_html"),
]

inventory/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.
class CategoryManager(models.Manager):
    
    def leaf_categories(self):
        ids = []
        for c in Category.objects.all():
            if not Category.objects.filter(parent_category=c).exists():
                ids.append(c.id)
        return Category.objects.filter(pk__in=ids)
        
    def root_categories(self):
        return Category.objects.filter(parent_category=None)


class Category(models.Model):
    
    objects = CategoryManager()
    
    name = models.CharField(max_length=55)
    parent_category = models.ForeignKey("Category", null=True, blank=True)
    
    def is_leaf_category(self):
        if Category.objects.leaf_categories().filter(pk=self.pk).exists():
            return True
        else:
            return False
            
    def __str__(self):
        return self.name
        
    def __repr__(self):
        return self.name
        
    def to_json(self, level=0):
        json = {
            "pk": self.id,
            "name": self.name,
            "level": level,
            "type": "c",
        }
        if self.category_set.all().exists():
            cats = []
            for cat in self.category_set.all():
                cats.append(cat.to_json(level + 1))
            json["categories"] = cats
        else:
            json["items"] = []
            for item in self.item_set.all():
                json["items"].append(item.to_json(level + 1))
        return json
        
    def save(self, *args, **kwargs):
        if not self.id and not self.parent_category is None:
            if self.name == "%s: Other" % self.parent_category.name:
                super(Category, self).save(*args, **kwargs)
                for item in self.parent_category.item_set.all():
                    item.category = self
                    item.save()
                return self
            else:
                sibling_children = Item.objects.filter(category=self.parent_category)
                if sibling_children.exists():
                    other_cat = Category.objects.get_or_create(name="%s: Other" % self.parent_category.name, parent_category=self.parent_category)
                return super(Category, self).save(*args, **kwargs)
        else:
            return super(Category, self).save(*args, **kwargs)
            
            
class ItemManager(models.Manager):
    
    def items_out(self):
        return ItemRecord.objects.filter(date_checked_in__isnull=True)
        
    def items_in(self):
        return Item.objects.filter(amount_left__gte=0)


class Item(models.Model):
    
    objects = ItemManager()
    
    name = models.CharField(max_length=55)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    total_amount = models.PositiveIntegerField(default=1)
    amount_left = models.PositiveIntegerField(default=1)
    category = models.ForeignKey(Category)
    
    def checkout(self, person, amount):
        return ItemRecord.objects.create(person=person, item=self, amount=amount)
    
    def __str__(self):
        return self.name
        
    def __repr__(self):
        return self.name
        
    def to_json(self, level=0):
        json = {
            "pk": self.id,
            "name": self.name,
            "description": self.description,
            "date_added": self.date_added.strftime("%D"),
            "total_amount": self.total_amount,
            "amount_left": self.amount_left,
            "level": level,
            "type": "i",
            "category__name": self.category.name,
            "records": [{
                "person": r.person,
                "date_checked_out": r.date_checked_out.strftime("%D"),
                "amount": r.amount,
                "type": "r",
                "id": r.id,
                "pk": r.pk,
            } for r in Item.objects.items_out().filter(item=self)]
        }
        
        return json
        
    def save(self, *args, **kwargs):
        sibling_cats = Category.objects.filter(parent_category=self.category)
        if sibling_cats.exists():
            self.category = Category.objects.get_or_create(name="%s: Other" % self.category.name, parent_category=self.category)[0]
        if self.pk is None:
            self.amount_left = self.total_amount
        return super(Item, self).save(*args, **kwargs)

        
class ItemRecord(models.Model):
    """docstring for ItemRecord"""
    
    person = models.CharField(max_length=50)
    item = models.ForeignKey(Item)
    date_checked_out = models.DateTimeField(auto_now_add=True)
    date_checked_in = models.DateTimeField(null=True, blank=True)
    amount = models.PositiveIntegerField(default=1)
    used_up = models.NullBooleanField()
    
    def to_json(self):
        if self.date_checked_in:
            dci = self.date_checked_in.strftime("%D")
        else:
            dci = "Not yet."
        if self.date_checked_out:
            dco = self.date_checked_out.strftime("%D")
        else:
            dco = "Not yet."
        return {
            "person": self.person,
            "item": self.item.to_json(),
            "item.name": self.item.name,
            "date_checked_in": dci,
            "date_checked_out": dco,
            "amount": self.amount,
            "used_up": self.used_up,
            "type": "r",
            "id": self.id,
            "pk": self.pk,
        }
    
    def use_up_item(self):
        item = Item.objects.get(id=self.item.id)
        item.total_amount -= self.amount
        item.save()
        self.date_checked_in = timezone.now()
        self.used_up = True
        self.save()
        if item.total_amount == 0:
            item.delete()
        return self
    
    def is_checkedin(self):
        if self.date_checked_in is None:
            return False
        else:
            return True
    
    def checkin(self):
        self.date_checked_in = timezone.now()
        item = Item.objects.get(id=self.item.id)
        item.amount_left = item.amount_left + self.amount
        self.used_up = False
        self.save()
        item.save()
        return self
    
    def save(self, *args, **kwargs):
        if not self.date_checked_in is None:
            record = super(ItemRecord, self).save(*args, **kwargs)
            return record
            
        item = Item.objects.get(id=self.item.id)
        if self.amount > item.amount_left:
            raise ValueError("There are not enough %ss left to take %s of them out. There are only %d left." % (self.item, self.amount, self.item.amount_left))
        else:
            record = super(ItemRecord, self).save(*args, **kwargs)
            self.item.amount_left = self.item.amount_left - self.amount
            self.item.save()
            return record
            
    def __str__(self):
        return "%s: %d %s" % (self.person, self.amount, self.item.name)
    
    def __repr__(self):
        return "%s: %d %s" % (self.person, self.amount, self.item.name)

inventory/forms.py
from django import forms

from inventory.models import Item, ItemRecord, Category

class CreateItemForm(forms.ModelForm):
    
    try:
        categories = Category.objects.all()
    except Exception, e:
        categories = []
    
    class Meta:
        model = Item
        exclude = ["date_added", "amount_left"]
        
    category = forms.ModelChoiceField(queryset=categories)

inventory/templates/inventory/add_item.html
{% extends 'inventory/site_base.html' %}

{% block title %}Add Item{% endblock title %}

{% load staticfiles %}
{% block css %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{% static 'css/add_item.css' %}" />
{% endblock %}

{% block content %}
<div class="content">
    <form id="item_add__form" action="" method="post">
        {% csrf_token %}
        <div class="form__field">
            <input id="id_name" maxlength="55" name="name" type="text" placeholder="Item Name:"></input>
            <div></div>
            <input id="id_total_amount" min="1" name="total_amount", type="number" placeholder="Amount:"></input>
        </div>
        <div class="form__field">
            <textarea cols="40" id="id_description" name="description" rows="10" placeholder="Description:"></textarea>
        </div>
        <div class="form__field">
            <label for="id_category">Category:</label>
            {{ form.category }}
        </div>
        <div class="form__field">
            <button class="form__submit" type="submit">Create Item</button>
            <button class="form__submit"><a href="{% url 'inv:items' %}">Cancel</a></button>
        </div>
    </form>
</div>
{% endblock content %}

inventory/templates/inventory/items.html
{% extends 'inventory/site_base.html' %}

{% block title %}Items{% endblock title %}

{% load staticfiles %}
{% block css %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{% static 'css/items.css' %}" />
{% endblock %}

{% block nav_right %}
<div class="header__link pointer highlight-red padding" id="show_items_out">
  <p class="txt-red no-margin no-padding">Items Out</p>
</div>
{% endblock %}

{% block content %}
{% csrf_token %}

<div class="layout_frame flex row left-to-right wrap" id="itemsin_navigation"></div>

  <div class="absolute h100 container_extras js-extras" id="items_out_container" hidden>
    <div class="flex no-margin h100 column left-to-right bg-white border-left border-gray">
      
      <div class="w100" id="list__container--items_out">
        <div class="list__header bg-red padding--small no-margin">
            <h3 class="txt-yellow--light no-padding no-margin">Items Out:</h3>
        </div>
        <div class="list__controls padding shadow">
            <input id="search-items-out" class="list_search__input" name="search-items-out" placeholder="Search an item or category."></input>
        </div>
        <div id="list-items-out">
        </div>
      </div>
      
    </div>
  </div>
  
  <div class="absolute h100 container_extras js-extras" id="itemsin_extras_container" hidden>
    <div class="flex no-margin h100 column left-to-right bg-white border-left border-gray">
      
      <div class="w100">
        <div class="list__header bg-red padding--small no-margin flex space-between middle">
          <h3 class="txt-yellow--light no-padding no-margin inline-block">Item Info and Actions</h3>
          <p class="inline-block no-margin margin-right--small btn-close txt-white" id="close_itemin_extras">
            &times;
          </p>
        </div>
        <div class="list__controls padding shadow">
          <p class="info_label js-itemin_name no-margin">ITEM_NAME</p>
        </div>
        <div class="padding-sides padding-bottom">
          <div class="info_group">
            <p class="info_label">DESCRIPTION:</p>
            <p class="info_data js-itemin_description">COB</p>
          </div>
          <div class="info_group">
            <p class="info_label">TOTAL AMOUNT:</p>
            <p class="info_data js-itemin_total_amount">COB</p>
          </div>
          <div class="info_group">
            <p class="info_label">AMOUNT LEFT:</p>
            <p class="info_data js-itemin_amount_left">COB</p>
          </div>
          <div class="info_group">
            <p class="info_label">CATEGORY:</p>
            <p class="info_data js-itemin_category">COB</p>
          </div>
          <div class="info_group">
            <p class="info_label">DATE ADDED:</p>
            <p class="info_data js-itemin_date_added">COB</p>
          </div>
          <div class="info_group">
            <p class="info_label">CHECKED OUT TO:</p>
            <input id="search_records_per_item" class="list_search__input" placeholder="Search a person."></input>
            <div id="itemin_records_list">
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>

{% endblock content %}

{% block custom_javascript %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/items.js' %}"></script>
<script type="text/javascript" src="{% static 'js/inventory/list_itemsin.js' %}"></script>
<script type="text/javascript" src="{% static 'js/inventory/list_itemsout.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function() {
    window.csrf = $("input[name='csrfmiddlewaretoken']").val();
    window.rootCategoryIn = new ListItemsIn(null);
    window.rootCategoryIn.render();
    window.itemsOutList = new ListItemsOut();
    window.itemsOutList.initialize();
    window.itemsinExtrasComponent = new ItemsInExtrasComponent();
  });
</script>
{% endblock custom_javascript %}

inventory/templates/inventory/site_base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %} | CMU Cru Inventory</title>
        <meta name="description" content="Item inventory for CMU Cru">
        
        {% load staticfiles %}
        {% block css %}
        <link type="text/css" rel="stylesheet" href="{% static 'css/global.css' %}"/>
        {% endblock css %}
        
        <script type="text/javascript" src="{% static 'js/fuse.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/fuzzy_search.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
        <script type="text/javascript" src="{% static 'jquery-ui-1.9.2/js/jquery-1.8.3.js' %}"></script>
    </head>
    <body>
        <nav class="flex space-between row bg-white--pure shadow padding-sides">
            <div class="flex left-to-right row">  
              <div class="margin--small">
                  <a href="{% url 'inv:items' %}"><div class="logo--cru" style="background-image: url({% static 'images/cru_logo.png' %})"></div></a>
              </div>
              <div class="flex">
                  {% if user.is_authenticated %}
                  <div class="header__link pointer highlight-red padding">
                    <a class="txt-red no-decoration" href="{% url 'logout' %}">Logout</a>
                  </div>
                  {% endif %}
                  
                  <div class="header__link pointer highlight-red padding">
                    <a class="txt-red no-decoration" href="{% url 'inv:add_item' %}">Add Item</a>
                  </div>
                  
                  {% if user.is_superuser %}
                  <div class="header__link pointer highlight-red padding">
                    <a class="txt-red no-decoration" href="/helm/">Helm</a>
                  </div>
                  {% endif %}
              </div>
            </div>
            <div class="flex left-to-right row">
              {% block nav_right %}
              {% endblock %}
            </div>
        </nav>
        <div class="body__container flex align-baseline">
            {% block content %}
            {% endblock content %}
        </div>
    
      {% block custom_javascript %}
      {% endblock custom_javascript %}
    </body>
</html>